config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { registrations: "registrations", confirmations: "confirmations" }
  devise_scope :user do
    authenticated :user do
      root 'welcome#index', as: :authenticated_root
    end

    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end
  resources :users, only: [:index, :show, :edit, :update, :destroy] do
    member do
      put :re_activate
    end
  end

  resources :publishers

  resources :contents do
    collection do
      get :datatable_ajax_content
    end
  end

  namespace :api do
    resources :inventory_imports do
      collection do
        put :import_all
        put :import_delta
      end
    end
  end

end

app/models/content.rb
class Content < ActiveRecord::Base
  belongs_to :publisher
  include ActiveModel::Dirty
end

app/controllers/contents_controller.rb
class ContentsController < ApplicationController

  def index
    @contents = Content.all
    authorize @contents
  end

  def datatable_ajax_content
    render json: ContentsDatatable.new(view_context)
  end

  def show
    @content = Content.find(params[:id])
    authorize @content
  end

  def new
    @content = Content.new
    authorize @content
  end

  def create
    @publisher = Publisher.find(params[:publisher_id])
    @content = @publisher.contents.new(content_params)
    authorize @content

    if @content.save
      flash[:success] = "The new content was successfully created."
      redirect_to @content
    else
      flash[:error] = "There was error creating the content. Please try again."
      render :new
    end
  end

  def edit
    @content = Content.find(params[:id])
    authorize @content
  end

  def update
    @publisher = Publisher.find(params[:publisher_id])
    @content = Content.find(params[:id])
    authorize @content

    if @content.update(content_params)
      @content.record_history(current_user)
      flash[:success] = "You have successfully updated the content."
      redirect_to @content
    else
      flash[:error] = "There was a problem updating the content. Please try again"
      render :edit
    end
  end

  def destroy
    @content = Content.find(params[:id])
    authorize @content

    if @content.destroy
      flash[:success] = "The content was successfully destroyed."
      redirect_to contents_path
    else
      flash[:error] = "There was a problem destroying the content. Please try again."
      render :show
    end
  end

  protected

  def content_params
    params.require(:content).permit(:kortext_id, :e_isbn, :p_isbn, :type_name, :format, :title, :author, :language,
    :pages, :description, :imprint, :pub_date, :price_gbp, :price_usd, :price_eur, :bic, :bisac, :content_image, :availabilty,
     :edition, :publisher_name, :vat)
  end
end

app/helpers/contents_helper.rb
module ContentsHelper
end

app/views/contents/edit.html.erb
<% content_for :content_header  do %>
  <section class="content-header">
    <h1>Contents <small>#edit</small></h1>
  </section>
<% end %>

<section class="content invoice">
  <p>Find me in app/views/contents/edit.html.erb</p>
</section>

app/views/contents/index.html.erb
<div class="row wrapper border-bottom white-bg page-heading">
  <div class="col-lg-10">
    <h2>Content Listing</h2>
    <ol class="breadcrumb">
      <li>
        <%= link_to authenticated_root_path do %>
          <i class="fa fa-dashboard"></i><span>  Home</span>
        <% end %>
      </li>
      <li>
        <%= link_to publishers_path do %>
          <i class="glyphicon glyphicon-briefcase"></i>
          Publishers
        <% end %>
      </li>
      <li class="active">
        <strong>Content</strong>
      </li>
    </ol>
  </div>
</div>
<div class="col-lg-2">
</div>
<div class="wrapper wrapper-content animated fadeInRight">
  <div class="row">
    <div class="col-lg-12">
      <div class="ibox float-e-margins">
        <div class="ibox-title">
          <h5>Content Data Table</h5>
          <div class="ibox-tools">
            <a class="collapse-link">
              <i class="fa fa-chevron-up"></i>
            </a>
            <a class="dropdown-toggle" data-toggle="dropdown" href="#">
              <i class="fa fa-wrench"></i>
            </a>
            <ul class="dropdown-menu dropdown-user">
                <li>
                    <%= link_to "Import Inventory", import_all_api_inventory_imports_path, method: :put %>
                </li>
                <li>
                    <%= link_to "Import Delta Inventory", import_delta_api_inventory_imports_path, method: :put %>
                </li>
            </ul>
            <a class="close-link">
                <i class="fa fa-times"></i>
            </a>
          </div>
        </div>
        <div class="ibox-content">
          <table class="table table-striped table-bordered table-hover dataTables-example" id="content_table">
            <%= link_to new_content_path, class: 'btn btn-primary' do %>
              <span class="glyphicon glyphicon-plus"></span>
              New Content
            <% end %>
            <thead>
              <tr>
                <th>Publisher</th>
                <th>Title</th>
                <th>Author</th>
                <th>e-isbn</th>
                <th>Availability</th>
                <th>Price GBP</th>
                <th>Price EUR</th>
                <th>Price USD</th>
                <th colspan="3">Actions</th>
              </tr>
            </thead>
            <tbody>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/contents/show.html.erb
<% content_for :content_header  do %>
  <section class="content-header">
    <h1>Contents <small>#show</small></h1>
  </section>
<% end %>

<section class="content invoice">
  <p>Find me in app/views/contents/show.html.erb</p>
</section>