config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { registrations: "registrations", confirmations: "confirmations" }
  devise_scope :user do
    authenticated :user do
      root 'welcome#index', as: :authenticated_root
    end

    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end
  resources :users, only: [:index, :show, :edit, :update, :destroy] do
    member do
      put :re_activate
    end
  end

  resources :publishers

  resources :contents do
    collection do
      get :datatable_ajax_content
    end
  end

  namespace :api do
    resources :inventory_imports do
      collection do
        put :import_all
        put :import_delta
      end
    end
  end

end

app/views/partials/_application_sidebar.html.erb
<section class="sidebar">
  <!-- Sidebar user panel -->
  <div class="user-panel">
    <div class="pull-left image">
      <%= image_tag attachment_url(current_user, :profile_image, :fill, 45, 45) %>
    </div>
    <div class="pull-left info">
      <p>Hello, <%= current_user.name %></p>

      <a href="#"><i class="fa fa-circle text-success"></i> Online</a>
    </div>
  </div>
  <!-- search form -->
  <form action="#" method="get" class="sidebar-form">
    <div class="input-group">
      <input type="text" name="q" class="form-control" placeholder="Search..."/>
      <span class="input-group-btn">
        <button type='submit' name='search' id='search-btn' class="btn btn-flat"><i class="fa fa-search"></i></button>
      </span>
    </div>
  </form>
  <!-- /.search form -->
  <!-- sidebar menu: : style can be found in sidebar.less -->
  <ul class="sidebar-menu">
    <%= nav_link edit_user_registration_path do %>
      <i class="fa fa-dashboard"></i><span>Dashboard</span>
    <% end %>
    <% if current_user.role == "admin" %>
      <%= nav_link users_path do %>
        <i class="fa fa-users"></i><span>User listing</span>
      <% end %>
    <% end %>
    <% if policy(Publisher.all).index? %>
      <%= nav_link publishers_path do %>
        <i class="glyphicon glyphicon-briefcase"></i><span>Publisher listing</span>
      <% end %>
    <% end %>
    <% if policy(Content.all).index? %>
      <%= nav_link contents_path do %>
        <i class="fa fa-book"></i><span>Content Listing</span>
      <% end %>
    <% end %>
    <%= treeview_link 'Lots of links here' do %>
      <%= nav_link "#" do %>
        <i class="fa fa-angle-double-right"></i>
        One Way
      <% end %>
      <%= nav_link "#" do %>
        <i class="fa fa-angle-double-right"></i>
        Another
      <% end %>
    <% end %>
  </ul>
</section>

app/views/partials/_flash.html.erb
<% flash.each do |name, msg| %>
  <%= content_tag :div, :class => "alert alert-#{ name == :error ? "danger" : "success" } alert-dismissable", :role => "alert" do %>
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">x</button>
    <%= msg %>
  <% end %>
<% end %>

app/views/partials/_footer.html.erb
<div class="footer">
    <div class="pull-right">
      Project <strong>Inca</strong>
    </div>
    <div>
      <strong>Copyright</strong> Alexander Robert Lewis &copy; 2014-2015
    </div>
</div>

app/views/partials/_head.html.erb
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Project Inca</title>
<!-- Main css styles -->
<%= stylesheet_link_tag    'application', media: 'all' %>
<!-- Main javascript files -->
<%= javascript_include_tag 'application' %>
<%= csrf_meta_tags %>
<%= favicon_link_tag "favicon.ico" %>

app/views/partials/_navigation.html.erb
<nav class="navbar-default navbar-static-side" role="navigation">
  <div class="sidebar-collapse">
    <ul class="nav metismenu" id="side-menu">
      <li class="nav-header">
        <div class="dropdown profile-element">
          <span>
            <%= image_tag attachment_url(current_user, :profile_image, :fill, 45, 45), class: "img-circle" %>
          </span>
          <a data-toggle="dropdown" class="dropdown-toggle" href="#">
            <span class="clear">
              <span class="block m-t-xs">
                <strong class="font-bold"><%= current_user.name %></strong>
              </span> <span class="text-muted text-xs block"> <%= current_user.role == "admin" ? "Admin User" : current_user.role == "moderator" ? "Moderator User" : "Standard" %> <b class="caret"></b></span>
            </span>
          </a>
          <ul class="dropdown-menu animated fadeInRight m-t-xs">
            <li>
              <%= link_to "Profile", edit_user_registration_path %>
            </li>
            <li>
              <a href="">Contacts</a>
            </li>
            <li>
              <a href="">Mailbox</a>
            </li>
            <li class="divider"></li>
            <li>
              <%= link_to "Logout", destroy_user_session_path, method: :delete %>
            </li>
          </ul>
        </div>
        <div class="logo-element">
          INCA
        </div>
      </li>
      <li>
        <%= nav_link edit_user_registration_path do %>
          <i class="fa fa-dashboard"></i><span class="nav-label">Dashboards</span><span class="fa arrow"></span>
        <% end %>
        <ul class="nav nav-second-level collapse ">

        </ul>
      </li>
      <li>
        <% if policy(User.all).index? %>
          <%= nav_link users_path do %>
            <i class="fa fa-users"></i><span class="nav-label">Users</span>
          <% end %>
        <% end %>
      </li>
      <li>
        <% if policy(Publisher.all).index? %>
          <%= nav_link publishers_path do %>
            <i class="glyphicon glyphicon-briefcase"></i><span class="nav-label">Publishers</span><span class="fa arrow"></span>
          <% end %>
        <% end %>
        <ul class="nav nav-second-level collapse">

        </ul>
      </li>
      <li>
        <% if policy(Content.all).index? %>
          <%= nav_link contents_path do %>
            <i class="fa fa-book"></i><span class="nav-label">Content</span>
          <% end %>
        <% end %>
        <ul class="nav nav-second-level collapse">

        </ul>
      </li>
      <li>
        <a href="#"><i class="fa fa-sitemap"></i><span class="nav-label">Menu Levels </span><span class="fa arrow"></span></a>
        <ul class="nav nav-second-level">
          <li>
            <a href="#">Third Level<span class="fa arrow"></span></a>
            <ul class="nav nav-third-level">
              <li>
                <a href="#">Third Level Item</a>
              </li>
              <li>
                <a href="#">Third Level Item</a>
              </li>
              <li>
                <a href="#">Third Level Item</a>
              </li>
            </ul>
          </li>
          <li>
            <a href="#">Second Level Item</a></li>
          <li>
            <a href="#">Second Level Item</a></li>
          <li>
          <a href="#">Second Level Item</a></li>
        </ul>
      </li>
    </ul>
  </div>
</nav>

app/views/partials/_rightsidebar.html.erb
<div id="right-sidebar">
  <div class="sidebar-container">
    <ul class="nav nav-tabs navs-3">
      <li class="active">
        <a data-toggle="tab" href="#tab-1">
          Notes
        </a>
      </li>
      <li>
        <a data-toggle="tab" href="#tab-2">
          Projects
        </a>
      </li>
      <li class="">
        <a data-toggle="tab" href="#tab-3">
          <i class="fa fa-gear"></i>
        </a>
      </li>
    </ul>
  <div class="tab-content">
    <div id="tab-1" class="tab-pane active">
      <div class="sidebar-title">
        <h3> <i class="fa fa-comments-o"></i> Latest Notes</h3>
        <small><i class="fa fa-tim"></i> You have 10 new message.</small>
      </div>
      <div>
      <div class="sidebar-message">
        <a href="#">
          <div class="pull-left text-center">
            <img alt="image" class="img-circle message-avatar" src="#">
            <div class="m-t-xs">
              <i class="fa fa-star text-warning"></i>
              <i class="fa fa-star text-warning"></i>
            </div>
          </div>
          <div class="media-body">
            There are many variations of passages of Lorem Ipsum available.
            <br>
            <small class="text-muted">Today 4:21 pm</small>
          </div>
        </a>
          </div>
          <div class="sidebar-message">
            <a href="#">
              <div class="pull-left text-center">
                <img alt="image" class="img-circle message-avatar" src="#">
              </div>
              <div class="media-body">
                The point of using Lorem Ipsum is that it has a more-or-less normal.
                <br>
                <small class="text-muted">Yesterday 2:45 pm</small>
              </div>
            </a>
          </div>
          <div class="sidebar-message">
            <a href="#">
              <div class="pull-left text-center">
                <img alt="image" class="img-circle message-avatar" src="#">
                <div class="m-t-xs">
                  <i class="fa fa-star text-warning"></i>
                  <i class="fa fa-star text-warning"></i>
                  <i class="fa fa-star text-warning"></i>
                </div>
              </div>
              <div class="media-body">
                Mevolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).
                <br>
                <small class="text-muted">Yesterday 1:10 pm</small>
              </div>
              </a>
          </div>
          <div class="sidebar-message">
            <a href="#">
              <div class="pull-left text-center">
                <img alt="image" class="img-circle message-avatar" src="#">
              </div>
              <div class="media-body">
                Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the
                <br>
                <small class="text-muted">Monday 8:37 pm</small>
              </div>
            </a>
          </div>
          <div class="sidebar-message">
            <a href="#">
              <div class="pull-left text-center">
                <img alt="image" class="img-circle message-avatar" src="#">
              </div>
              <div class="media-body">
                All the Lorem Ipsum generators on the Internet tend to repeat.
                <br>
                <small class="text-muted">Today 4:21 pm</small>
              </div>
            </a>
          </div>
          <div class="sidebar-message">
            <a href="#">
              <div class="pull-left text-center">
                <img alt="image" class="img-circle message-avatar" src="#">
              </div>
              <div class="media-body">
                Renaissance. The first line of Lorem Ipsum, "Lorem ipsum dolor sit amet..", comes from a line in section 1.10.32.
                <br>
                <small class="text-muted">Yesterday 2:45 pm</small>
              </div>
            </a>
          </div>
          <div class="sidebar-message">
            <a href="#">
              <div class="pull-left text-center">
                <img alt="image" class="img-circle message-avatar" src="#">
                <div class="m-t-xs">
                  <i class="fa fa-star text-warning"></i>
                  <i class="fa fa-star text-warning"></i>
                  <i class="fa fa-star text-warning"></i>
                </div>
              </div>
              <div class="media-body">
                The standard chunk of Lorem Ipsum used since the 1500s is reproduced below.
                <br>
                <small class="text-muted">Yesterday 1:10 pm</small>
              </div>
            </a>
          </div>
          <div class="sidebar-message">
            <a href="#">
              <div class="pull-left text-center">
                <img alt="image" class="img-circle message-avatar" src="#">
              </div>
              <div class="media-body">
                Uncover many web sites still in their infancy. Various versions have.
                <br>
                <small class="text-muted">Monday 8:37 pm</small>
              </div>
            </a>
          </div>
        </div>
      </div>
      <div id="tab-2" class="tab-pane">
        <div class="sidebar-title">
          <h3> <i class="fa fa-cube"></i> Latest projects</h3>
          <small><i class="fa fa-tim"></i> You have 14 projects. 10 not completed.</small>
        </div>
        <ul class="sidebar-list">
          <li>
            <a href="#">
              <div class="small pull-right m-t-xs">9 hours ago</div>
              <h4>Business valuation</h4>
              It is a long established fact that a reader will be distracted.
              <div class="small">Completion with: 22%</div>
              <div class="progress progress-mini">
                <div style="width: 22%;" class="progress-bar progress-bar-warning"></div>
              </div>
              <div class="small text-muted m-t-xs">Project end: 4:00 pm - 12.06.2014</div>
            </a>
          </li>
          <li>
            <a href="#">
              <div class="small pull-right m-t-xs">9 hours ago</div>
              <h4>Contract with Company </h4>
              Many desktop publishing packages and web page editors.
              <div class="small">Completion with: 48%</div>
              <div class="progress progress-mini">
                <div style="width: 48%;" class="progress-bar"></div>
              </div>
            </a>
          </li>
          <li>
            <a href="#">
              <div class="small pull-right m-t-xs">9 hours ago</div>
              <h4>Meeting</h4>
              By the readable content of a page when looking at its layout.
              <div class="small">Completion with: 14%</div>
              <div class="progress progress-mini">
                <div style="width: 14%;" class="progress-bar progress-bar-info"></div>
              </div>
            </a>
          </li>
          <li>
            <a href="#">
              <span class="label label-primary pull-right">NEW</span>
              <h4>The generated</h4>
              <!--<div class="small pull-right m-t-xs">9 hours ago</div>-->
              There are many variations of passages of Lorem Ipsum available.
              <div class="small">Completion with: 22%</div>
              <div class="small text-muted m-t-xs">Project end: 4:00 pm - 12.06.2014</div>
            </a>
          </li>
          <li>
            <a href="#">
              <div class="small pull-right m-t-xs">9 hours ago</div>
              <h4>Business valuation</h4>
              It is a long established fact that a reader will be distracted.
              <div class="small">Completion with: 22%</div>
              <div class="progress progress-mini">
                <div style="width: 22%;" class="progress-bar progress-bar-warning"></div>
              </div>
              <div class="small text-muted m-t-xs">Project end: 4:00 pm - 12.06.2014</div>
            </a>
          </li>
          <li>
            <a href="#">
              <div class="small pull-right m-t-xs">9 hours ago</div>
              <h4>Contract with Company </h4>
              Many desktop publishing packages and web page editors.
              <div class="small">Completion with: 48%</div>
              <div class="progress progress-mini">
                <div style="width: 48%;" class="progress-bar"></div>
              </div>
            </a>
          </li>
          <li>
            <a href="#">
              <div class="small pull-right m-t-xs">9 hours ago</div>
              <h4>Meeting</h4>
              By the readable content of a page when looking at its layout.
              <div class="small">Completion with: 14%</div>
              <div class="progress progress-mini">
                <div style="width: 14%;" class="progress-bar progress-bar-info"></div>
              </div>
            </a>
          </li>
          <li>
            <a href="#">
              <span class="label label-primary pull-right">NEW</span>
              <h4>The generated</h4>
              <!--<div class="small pull-right m-t-xs">9 hours ago</div>-->
              There are many variations of passages of Lorem Ipsum available.
              <div class="small">Completion with: 22%</div>
              <div class="small text-muted m-t-xs">Project end: 4:00 pm - 12.06.2014</div>
            </a>
          </li>
        </ul>
      </div>
      <div id="tab-3" class="tab-pane">
        <div class="sidebar-title">
          <h3><i class="fa fa-gears"></i> Settings</h3>
          <small><i class="fa fa-tim"></i> You have 14 projects. 10 not completed.</small>
        </div>
        <div class="setings-item">
          <span>
            Show notifications
          </span>
          <div class="switch">
            <div class="onoffswitch">
              <input type="checkbox" name="collapsemenu" class="onoffswitch-checkbox" id="example">
              <label class="onoffswitch-label" for="example">
                <span class="onoffswitch-inner"></span>
                <span class="onoffswitch-switch"></span>
              </label>
            </div>
          </div>
        </div>
        <div class="setings-item">
          <span>
            Disable Chat
          </span>
          <div class="switch">
            <div class="onoffswitch">
              <input type="checkbox" name="collapsemenu" checked class="onoffswitch-checkbox" id="example2">
              <label class="onoffswitch-label" for="example2">
                <span class="onoffswitch-inner"></span>
                <span class="onoffswitch-switch"></span>
              </label>
            </div>
          </div>
        </div>
        <div class="setings-item">
          <span>
            Enable history
          </span>
          <div class="switch">
            <div class="onoffswitch">
              <input type="checkbox" name="collapsemenu" class="onoffswitch-checkbox" id="example3">
              <label class="onoffswitch-label" for="example3">
                <span class="onoffswitch-inner"></span>
                <span class="onoffswitch-switch"></span>
              </label>
            </div>
          </div>
        </div>
        <div class="setings-item">
          <span>
            Show charts
          </span>
          <div class="switch">
            <div class="onoffswitch">
              <input type="checkbox" name="collapsemenu" class="onoffswitch-checkbox" id="example4">
              <label class="onoffswitch-label" for="example4">
                  <span class="onoffswitch-inner"></span>
                  <span class="onoffswitch-switch"></span>
              </label>
            </div>
          </div>
        </div>
        <div class="setings-item">
          <span>
            Offline users
          </span>
          <div class="switch">
            <div class="onoffswitch">
              <input type="checkbox" checked name="collapsemenu" class="onoffswitch-checkbox" id="example5">
              <label class="onoffswitch-label" for="example5">
                <span class="onoffswitch-inner"></span>
                <span class="onoffswitch-switch"></span>
              </label>
            </div>
          </div>
        </div>
        <div class="setings-item">
          <span>
            Global search
          </span>
          <div class="switch">
            <div class="onoffswitch">
              <input type="checkbox" checked name="collapsemenu" class="onoffswitch-checkbox" id="example6">
              <label class="onoffswitch-label" for="example6">
                <span class="onoffswitch-inner"></span>
                <span class="onoffswitch-switch"></span>
              </label>
            </div>
          </div>
        </div>
        <div class="setings-item">
          <span>
            Update everyday
          </span>
          <div class="switch">
            <div class="onoffswitch">
              <input type="checkbox" name="collapsemenu" class="onoffswitch-checkbox" id="example7">
              <label class="onoffswitch-label" for="example7">
                <span class="onoffswitch-inner"></span>
                <span class="onoffswitch-switch"></span>
              </label>
            </div>
          </div>
        </div>
        <div class="sidebar-content">
          <h4>Settings</h4>
          <div class="small">
            I belive that. Lorem Ipsum is simply dummy text of the printing and typesetting industry.
            And typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s.
            Over the years, sometimes by accident, sometimes on purpose (injected humour and the like).
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/partials/_topnavbar.html.erb
<div class="row border-bottom">
  <nav class="navbar navbar-static-top" role="navigation" style="margin-bottom: 0">
    <div class="navbar-header">
      <a class="navbar-minimalize minimalize-styl-2 btn btn-primary " href="#"><i class="fa fa-bars"></i> </a>
      <form role="search" class="navbar-form-custom" method="post" action="">
        <div class="form-group">
          <input type="text" placeholder="Search for something..." class="form-control" name="top-search" id="top-search"/>
        </div>
      </form>
    </div>
    <ul class="nav navbar-top-links navbar-right">
      <!-- <li>
        <span class="m-r-sm text-muted welcome-message">Welcome to INSPINIA+ Admin Theme.</span>
      </li> -->
      <li class="dropdown">
        <a class="dropdown-toggle count-info" data-toggle="dropdown" href="#">
          <i class="fa fa-envelope"></i>  <span class="label label-warning">16</span>
        </a>
        <ul class="dropdown-menu dropdown-messages">
          <li>
            <div class="dropdown-messages-box">
              <a href="#" class="pull-left">
                <img alt="image" class="img-circle" src="#" />
              </a>
              <div class="media-body">
                <small class="pull-right">46h ago</small>
                <strong>Mike Loreipsum</strong> started following <strong>Monica Smith</strong>. <br/>
                <small class="text-muted">3 days ago at 7:58 pm - 10.06.2014</small>
              </div>
            </div>
          </li>
          <li class="divider"></li>
          <li>
            <div class="dropdown-messages-box">
              <a href="#" class="pull-left">
                <img alt="image" class="img-circle" src="#" />
              </a>
              <div class="media-body ">
                <small class="pull-right text-navy">5h ago</small>
                <strong>Chris Johnatan Overtunk</strong> started following <strong>Monica Smith</strong>. <br/>
                <small class="text-muted">Yesterday 1:21 pm - 11.06.2014</small>
              </div>
            </div>
          </li>
          <li class="divider"></li>
          <li>
            <div class="dropdown-messages-box">
              <a href="#" class="pull-left">
                <img alt="image" class="img-circle" src="#" />
              </a>
              <div class="media-body ">
                <small class="pull-right">23h ago</small>
                <strong>Monica Smith</strong> love <strong>Kim Smith</strong>. <br/>
                <small class="text-muted">2 days ago at 2:30 am - 11.06.2014</small>
              </div>
            </div>
          </li>
          <li class="divider"></li>
          <li>
            <div class="text-center link-block">
              <a href="#">
                <i class="fa fa-envelope"></i> <strong>Read All Messages</strong>
              </a>
            </div>
          </li>
        </ul>
      </li>
      <li class="dropdown">
        <a class="dropdown-toggle count-info" data-toggle="dropdown" href="#">
            <i class="fa fa-bell"></i>  <span class="label label-primary">8</span>
        </a>
        <ul class="dropdown-menu dropdown-alerts">
          <li>
            <a href="#">
              <div>
                <i class="fa fa-envelope fa-fw"></i> You have 16 messages
                <span class="pull-right text-muted small">4 minutes ago</span>
              </div>
            </a>
          </li>
          <li class="divider"></li>
          <li>
            <a href="#">
              <div>
                <i class="fa fa-twitter fa-fw"></i> 3 New Followers
                <span class="pull-right text-muted small">12 minutes ago</span>
              </div>
            </a>
          </li>
          <li class="divider"></li>
          <li>
            <a href="#">
              <div>
                <i class="fa fa-upload fa-fw"></i> Server Rebooted
                <span class="pull-right text-muted small">4 minutes ago</span>
              </div>
            </a>
          </li>
          <li class="divider"></li>
          <li>
            <div class="text-center link-block">
              <a href="#">
                <strong>See All Alerts</strong>
                <i class="fa fa-angle-right"></i>
              </a>
            </div>
          </li>
        </ul>
      </li>
      <li>
        <%= link_to destroy_user_session_path, method: :delete do %>
          <i class="fa fa-sign-out"></i><span>Logout</span>
        <% end %>
      </li>
      <li>
        <a class="right-sidebar-toggle">
          <i class="fa fa-tasks"></i>
        </a>
      </li>
    </ul>
  </nav>
</div>