config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { registrations: "registrations", confirmations: "confirmations" }
  devise_scope :user do
    authenticated :user do
      root 'welcome#index', as: :authenticated_root
    end

    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end
  resources :users, only: [:index, :show, :edit, :update, :destroy] do
    member do
      put :re_activate
    end
  end

  resources :publishers

  resources :contents do
    collection do
      get :datatable_ajax_content
    end
  end

  namespace :api do
    resources :inventory_imports do
      collection do
        put :import_all
        put :import_delta
      end
    end
  end

end

app/models/user.rb
class User < ActiveRecord::Base

  # Soft delete implementation using paranoid gem
  acts_as_paranoid

  include ActiveModel::Dirty

  # Include default devise modules. Others available are:
  # :lockable, :timeoutable and :omniauthable
  devise :invitable, :database_authenticatable, :registerable, :invitable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

  # Associations
  has_many :histories

  # Refile method
  attachment :profile_image, type: :image

  # role assignement to determine User authority
  enum role: { standard: 0, moderator: 1, admin: 2 }

  # Custom validations
  validates :name, presence: true

  protected

  def admin
    self.role == "admin"
  end

  def admin_invite
    if admin?
      self.update(invitation_limit: 1000)
    else
      self.update(invitation_limit: 0)
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_admin_user!
  before_action :set_user, except: [:index]

  def index
    @users = User.with_deleted
    authorize @users
  end

  def show

  end

  def edit

  end

  def update
    if @user.update(user_params)
      @user.admin_invite
      @user.record_history(current_user)
      flash[:success] = "User was successfully updated"
      redirect_to @user
    else
      flash[:error] = "There was an error updated this user. Please try again!"
      render :edit
    end
  end

  def re_activate
    @user.update(deleted_at: nil)
    respond_to do |format|
      format.json { render json: @users }
    end
  end

  def destroy
    @user.destroy
    respond_to do |format|
      format.json { render json: @users }
    end
  end

  protected

  def set_user
    @user = User.with_deleted.find(params[:id])
    authorize @user
  end

  def user_params
    params.require(:user).permit(:role)
  end

end

app/helpers/users_helper.rb
module UsersHelper

end

app/views/users/_edit.html.erb
<div class="modal inmodal" id=<%="userEditModal_#{index}"%> tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content animated fadeIn">
      <section class="content-header">
        <h1> User: <small><%= user.name %></small></h1>

        <ol class="breadcrumb">
          <li>
              <%= link_to authenticated_root_path do %>
                <i class="fa fa-dashboard"></i>
              <% end %>
          </li>
          <li><%= link_to "Users", users_path %></li>
          <li class="active"><%= user.name %></li>
        </ol>
      </section>

      <section class="content invoice">
        <div class="row">
          <div class="col-md-10">
            <% if policy(user).update? %>
              <%= form_for user do |f| %>
                <% if user.errors.any? %>
                  <div class="alert alert-danger alert-dismissable" role="alert">
                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">x</button>
                    <h4><%= pluralize(user.errors.count, "error") %> prohibited this User from being updated:</h4>

                    <ul>
                    <% user.errors.full_messages.each do |msg| %>
                      <li><%= msg %></li>
                    <% end %>
                    </ul>
                  </div>
                <% end %>
                <div class="form-group">
                  <%= f.label :role %>
                  <%= f.select(:role, %w(standard moderator admin), prompt: "assign a role") %>
                </div>
                <div class="form-group">
                  <%= f.button "Update", class: "btn btn-md btn-primary", data: { disable_with: "<i class='fa fa-spinner'></i>Updating......" } %>
                </div>
              <% end %>
            <% end %>
            <%= link_to "back", :back %>
          </div>
        </div>
      </section>
    </div>
  </div>
</div>

app/views/users/_show.html.erb
<div class="modal inmodal" id=<%="userShowModal_#{index}"%> tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content animated fadeIn">
          <section class="content-header">
            <h1> User: <small><%= user.name %></small></h1>

            <ol class="breadcrumb">
              <li>
                  <%= link_to authenticated_root_path do %>
                    <i class="fa fa-dashboard"></i>
                  <% end %>
              </li>
              <li><%= link_to "Users", users_path %></li>
              <li class="active">Show</li>
            </ol>
          </section>

          <section class="content">
            <div class="row">
              <div class="col-md-12">
                <div class="box box-primary">
                  <div class="box-header">
                    <div class="box-tools pull-right">
                      <% if policy(user).destroy? %>
                        <%= link_to user_path(user), class: "btn btn-warning", method: :delete, data: { confirm: "Are you sure?" } do %>
                          <span class="glyphicon glyphicon-remove"></span>
                          Delete
                        <% end %>
                      <% end %>
                    </div>
                    <div class="box-tools pull-right">
                      <% if policy(user).edit? %>
                        <%= link_to edit_user_path(user), class: "btn btn-primary" do %>
                          <span class="glyphicon glyphicon-pencil"></span>
                          Edit
                        <% end %>
                      <% end %>
                    </div>
                  </div>
                  <div class="box-body">
                    <dl class="dl-horizontal">
                        <dt>ID:</dt>
                          <dd><%= user.id %></dd>
                        <dt>Email:</dt>
                          <dd><%= user.email %></dd>
                        <dt>Confirmed:</dt>
                          <dd>
                              <% if user.confirmed_at %>
                                Yes
                              <% else %>
                                No
                              <% end %>
                          </dd>
                        <dt>Last Login:</dt>
                          <dd><%= user.last_sign_in_at %></dd>
                        <dt>Admin user?:</dt>
                          <dd><%= user.role %></dd>
                    </dl>
                  </div>
                </div>
              </div>
            </div>
          </section>
        </div>
    </div>
</div>

app/views/users/index.html.erb
<div class="row wrapper border-bottom white-bg page-heading">
  <div class="col-lg-10">
    <h2>Users Listing</h2>
    <ol class="breadcrumb">
      <li>
        <%= link_to authenticated_root_path do %>
          <i class="fa fa-dashboard"></i><span>  Home</span>
        <% end %>
      </li>
      <li class="active">
        <strong>Users</strong>
      </li>
    </ol>
  </div>
</div>
<div class="col-lg-2">
</div>
<div class="wrapper wrapper-content animated fadeInRight">
  <div class="row">
    <div class="col-lg-12">
      <div class="ibox float-e-margins">
        <div class="ibox-title">
          <h5>Users Data Table</h5>
          <div class="ibox-tools">
            <a class="collapse-link">
              <i class="fa fa-chevron-up"></i>
            </a>
            <a class="dropdown-toggle" data-toggle="dropdown" href="#">
              <i class="fa fa-wrench"></i>
            </a>
            <ul class="dropdown-menu dropdown-user">
                <li>
                    <a href="#">Config option 1</a>
                </li>
                <li>
                    <a href="#">Config option 2</a>
                </li>
            </ul>
            <a class="close-link">
                <i class="fa fa-times"></i>
            </a>
          </div>
        </div>
        <div class="ibox-content">
          <table class="table table-striped table-bordered table-hover dataTables-example" id="user_table">
            <%= link_to "#userInvitationModal", data: { toggle: "modal" }, class: "btn btn-primary" do %>
              <i class="glyphicon glyphicon-plus"></i>
              New user
              <%= render "devise/invitations/new" %>
            <% end %>
            <thead>
              <tr>
                <th>Name</th>
                <th>Email</th>
                <th>Admin?</th>
                <th>Confirmed?</th>
                <th>Active?</th>
                <th colspan="3">Actions</th>
              </tr>
            </thead>
            <tbody>
              <% @users.each_with_index do |user, index| %>
                <tr>
                  <td><%= user.name %></td>
                  <td><%= user.email %></td>
                  <td><%= user.role %></td>
                  <td>
                    <% if user.confirmed? %>
                      <span class="label label-success">confirmed</span>
                    <% else %>
                      <span class="label label-warning">unconfirmed</span>
                    <% end %>
                  </td>
                  <td>
                    <% if user.deleted_at == nil %>
                      <span class="label label-primary active">Active</span>
                    <% else %>
                      <span class="label label-warning active">Archived</span>
                    <% end %>
                  </td>
                  <td>
                    <%= link_to "#userShowModal_#{index}", data: { toggle: "modal" } do %>
                      <i class="glyphicon glyphicon-user"></i>
                      <%= render partial: "show", locals: { user: user, index: index } %>
                    <% end %>
                  </td>
                  <td>
                    <%= link_to "#userEditModal_#{index}", data: { toggle: "modal" } do %>
                      <i class="glyphicon glyphicon-pencil"></i>
                      <%= render partial: "edit", locals: { user: user, index: index } %>
                    <% end %>
                  </td>
                  <td>
                    <% if user.deleted_at != nil %>
                      <%= link_to re_activate_user_path(user), data: { behavior: "confirmRestore", type: "#{user.class}" }, method: :put do %>
                        <i class="glyphicon glyphicon-ok"></i>
                      <% end %>
                    <% else %>
                      <%= link_to user_path(user), data: { behavior: "confirmDelete", type: "#{user.class}" } do %>
                        <i class="glyphicon glyphicon-remove"></i>
                      <% end %>
                    <% end %>
                  </td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>