config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { registrations: "registrations", confirmations: "confirmations" }
  devise_scope :user do
    authenticated :user do
      root 'welcome#index', as: :authenticated_root
    end

    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end
  resources :users, only: [:index, :show, :edit, :update, :destroy] do
    member do
      put :re_activate
    end
  end

  resources :publishers

  resources :contents do
    collection do
      get :datatable_ajax_content
    end
  end

  namespace :api do
    resources :inventory_imports do
      collection do
        put :import_all
        put :import_delta
      end
    end
  end

end

app/models/publisher.rb
class Publisher < ActiveRecord::Base
  has_many :contents, dependent: :destroy
  include ActiveModel::Dirty

end

app/controllers/publishers_controller.rb
class PublishersController < ApplicationController
  before_action :set_publisher, except: [:index, :new, :create]

  def index
    @publishers = Publisher.all
    authorize @publishers
  end

  def show

  end

  def new
    @publisher = Publisher.new
    authorize @publisher
  end

  def create

    @publisher = Publisher.new(pub_params)
    authorize @publisher
    if @publisher.save
      flash[:success] = "The Publisher was successfully created."
      redirect_to @publisher
    else
      flash[:error] = "There was an error updating the Publisher. Please try again."
      render :new
    end
  end

  def edit

  end

  def update

    if @publisher.update(pub_params)
      @publisher.record_history(current_user)
      flash[:success] = "The Publisher's details were successfully updated."
      redirect_to @publisher
    else
      flash[:error] = "There was an error updating the Publisher. Please try again."
      render :edit
    end
  end

  def destroy

    if @publisher.destroy
      flash[:success] = "The Publisher was successfully destroyed."
      redirect_to publishers_path
    else
      flash[:error] = "There was an error destroying the Publisher. Please try again."
      render :edit
    end
  end

  protected

  def set_publisher
    @publisher = Publisher.find(params[:id])
    authorize @publisher
  end

  def pub_params
    params.require(:publisher).permit(:name, :address, :contract_start_date, :contract_end_date)
  end
end

app/helpers/publishers_helper.rb
module PublishersHelper
end

app/views/publishers/_form.html.erb
<section class="content invoice">
  <div class="row">
    <div class="col-md-10">
      <% if policy(@publisher).new? %>
        <%= form_for @publisher do |f| %>
          <% if @publisher.errors.any? %>
            <div class="alert alert-danger alert-dismissable" role="alert">
              <button type="button" class="close" data-dismiss="alert" aria-hidden="true">x</button>
              <h4><%= pluralize(@publisher.errors.count, "error") %> prohibited this User from being updated:</h4>

              <ul>
              <% @publisher.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
              <% end %>
              </ul>
            </div>
          <% end %>
          <div class="form-group">
            <%= f.label :name %>
            <%= f.text_field :name, class: "form-control text-area", placeholder: "Enter name" %>
          </div>
          <div class="form-group">
            <%= f.label :address %>
            <%= f.text_area :address, class: "form-control text-area", placeholder: "Enter address", rows: "15" %>
          </div>
          <div class="form-group">
            <%= f.label :contract_start_date %>
            <%= f.date_field :contract_start_date %>
          </div>
          <div class="form-group">
            <%= f.label :contract_end_date %>
            <%= f.date_field :contract_end_date %>
          </div>
          <div class="form-group">
            <%= f.button class: "btn btn-md btn-primary", data: { disable_with: "<i class='fa fa-spinner'></i>Updating......" } do %>
              <% if @publisher.name %>
                Update
              <% else %>
                Create
              <% end %>
            <% end %>
          </div>
        <% end %>
      <% end %>
      <%= link_to "back", :back %>
    </div>
  </div>
</section> 

app/views/publishers/edit.html.erb
<section class="content-header">
  <h1> Publisher: <small><%= @publisher.name %></small></h1>

  <ol class="breadcrumb">
    <li>
        <%= link_to authenticated_root_path do %>
          <i class="fa fa-dashboard"></i>
        <% end %>
    </li>
    <li><%= link_to "publishers", publishers_path %></li>
    <li class="active"><%= @publisher.name %></li>
  </ol>
</section>

<%= render "form" %>

app/views/publishers/index.html.erb
<div class="row wrapper border-bottom white-bg page-heading">
  <div class="col-lg-10">
    <h2>Publishers Listing</h2>
    <ol class="breadcrumb">
      <li>
        <%= link_to authenticated_root_path do %>
          <i class="fa fa-dashboard"></i><span>  Home</span>
        <% end %>
      </li>
      <li class="active">
        <strong>Publishers</strong>
      </li>
    </ol>
  </div>
</div>
<div class="col-lg-2">
</div>
<div class="wrapper wrapper-content animated fadeInRight">
  <div class="row">
    <div class="col-lg-12">
      <div class="ibox float-e-margins">
        <div class="ibox-title">
          <h5>Publishers Data Table</h5>
          <div class="ibox-tools">
            <a class="collapse-link">
              <i class="fa fa-chevron-up"></i>
            </a>
            <a class="dropdown-toggle" data-toggle="dropdown" href="#">
              <i class="fa fa-wrench"></i>
            </a>
            <ul class="dropdown-menu dropdown-user">
                <li>
                    <a href="#">Config option 1</a>
                </li>
                <li>
                    <a href="#">Config option 2</a>
                </li>
            </ul>
            <a class="close-link">
                <i class="fa fa-times"></i>
            </a>
          </div>
        </div>
        <div class="ibox-content">
          <table class="table table-striped table-bordered table-hover dataTables-example" id="publisher_table">
            <%= link_to new_publisher_path, class: 'btn btn-primary' do %>
              <span class="glyphicon glyphicon-plus"></span>
              New Publisher
            <% end %>
            <thead>
              <tr>
                <th>Name</th>
                <th>Address</th>
                <th>Contract signed</th>
                <th>Contract End</th>
                <th colspan="3">Actions</th>
              </tr>
            </thead>
            <tbody>
              <% @publishers.each do |publisher| %>
                <tr>
                  <td><%= publisher.name %></td>
                  <td><%= publisher.address %></td>
                  <td><%= publisher.contract_start_date %></td>
                  <td><%= publisher.contract_end_date %></td>
                  <td>
                    <% if policy(publisher).show? %>
                      <%= link_to publisher do %>
                        <i class="glyphicon glyphicon-briefcase"></i>
                      <% end %>
                    <% end %>
                  </td>
                  <td>
                    <% if policy(publisher).edit? %>
                      <%= link_to edit_publisher_path(publisher) do %>
                        <i class="glyphicon glyphicon-pencil"></i>
                      <% end %>
                    <% end %>
                  </td>
                  <td>
                    <% if policy(publisher).destroy? %>
                      <%= link_to publisher_path(publisher), method: :delete, data: { confirm: "Are you sure?" } do %>
                        <i class="glyphicon glyphicon-remove"></i>
                      <% end %>
                    <% else %>
                      "n/a"
                    <% end %>
                  </td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/publishers/new.html.erb
<section class="content-header">
  <h1> Publisher: <small>new publisher</small></h1>

  <ol class="breadcrumb">
    <li>
        <%= link_to authenticated_root_path do %>
          <i class="fa fa-dashboard"></i>
        <% end %>
    </li>
    <li><%= link_to "publishers", publishers_path %></li>
    <li class="active">new publisher</li>
  </ol>
</section>

<%= render "form" %>

app/views/publishers/show.html.erb
<section class="content-header">
  <h1> Publisher: <small><%= @publisher.name %></small></h1>

  <ol class="breadcrumb">
    <li>
        <%= link_to authenticated_root_path do %>
          <i class="fa fa-dashboard"></i>
        <% end %>
    </li>
    <li><%= link_to "publishers", publishers_path %></li>
    <li class="active">Show</li>
  </ol>
</section>

<section class="content">
  <div class="row">
    <div class="col-md-12">
      <div class="box box-primary">
        <div class="box-header">
          <div class="box-tools pull-right">
            <% if policy(@publisher).destroy? %>
              <%= link_to publisher_path, class: "btn btn-warning", method: :delete, data: { confirm: "Are you sure?" } do %>
                <span class="glyphicon glyphicon-remove"></span>
                Delete
              <% end %>   
            <% end %>       
          </div>
          <div class="box-tools pull-right">
            <% if policy(@publisher).edit? %>
              <%= link_to edit_publisher_path, class: "btn btn-primary" do %>
                <span class="glyphicon glyphicon-pencil"></span>
                Edit
              <% end %>
            <% end %>          
          </div>
        </div>
        <div class="box-body">
          <dl class="dl-horizontal">
              <dt>ID:</dt> 
                <dd><%= @publisher.attributes["id"] %></dd>
              <dt>Address:</dt> 
                <dd><%= @publisher.attributes["address"] %></dd>
              <dt>Contract start date:</dt> 
                <dd><%= @publisher.attributes["contract_start_date"] %></dd>
              <dt>Contract end date:</dt> 
                <dd><%= @publisher.attributes["contract_end_date"] %></dd>
              <%= link_to "back", :back %>
          </dl>
        </div>
      </div>
    </div>
  </div>
</section>